# FlagGame Configuration file!
# @author syamn <admin@sakura-server.net>
# github: https://github.com/syamn/FlagGame

#==================#
#   Basic Config   #
#==================#
# ItemID, used to create/remove Flag blocks
ToolID: 269

#==================#
#   DO NOT TOUCH   #
#==================#
# Do not touch this option! It is a check if you are running the recent configuration version
Version: 0.1