##  Plugin Information  ##
name: FlagGame
version: 0.1
main: syam.FlagGame.FlagGame
description: FlagMatch Gaming Plugin for SakuraServer
website: http://sakura-server.net/
depend: [Vault, WorldEdit]
softdepend: [DeathNotifier]
##  Original Author     ##
author: syam
commands:
    flag:
      usage: /flag - to see the help
      aliases: [f, fg]
      description: To see the FlagGame help.
permissions:
    flag.user.join:
        default: op
        description: Allow join the game
    flag.admin:
        default: op
        description: Allow all of administer commands
    flag.admin.sign:
        default: op
        description: Allow place FlagGame sign
    flag.ignoreWorldProtect:
        default: op
        description: Allow Break/Place protected game-world
    flag.admin.reload:
        default: op
        description: Allow reload configuration
    flag.admin.save:
        default: op
        description: Allow save map data